
name: Deploy Github Pages

on:
  push:
    paths-ignore:
      - '.gitignore'
      - '.stylelintrc.json'
      - 'README.md'

jobs:
  build-and-deploy:
    name: Github Pages Deploy
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: install package
        run: |
          yarn install --frozen-lockfile
      - name: lint
        run: |
          yarn lint:css
      - name: build
        run: |
          yarn build
      - name: deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist